# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
 paths:
   include:
     - analytics-service/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '1f669a09-12f5-4a11-b9e1-1634d7a0af2e'
  imageRepository: 'analytics-service-app'
  containerRegistry: 'chiradev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/analytics-service/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
 name: 'azureagent' 

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'analytics-service/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName: push
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        Dockerfile: 'analytics-service/Dockerfile'
        tags: '$(tag)'