apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
  namespace: polling-platform
  labels:
    app: vote-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-service
  template:
    metadata:
      labels:
        app: vote-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: vote-service
          image: chiradev.azurecr.io/vote-service:12
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: polling-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: polling-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: polling-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: polling-config
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: polling-config
                  key: SPRING_REDIS_PORT
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: polling-secrets
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8083
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: vote-service-svc
  namespace: polling-platform
spec:
  selector:
    app: vote-service
  ports:
    - port: 8083
      targetPort: 8083
